<a href="https://colab.research.google.com/github/aibak365/Machine-learning/blob/main/CSE432_532_DT_RF_IRIS_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix
# from sklearn.tree import DecisionTreeClassifier
from sklearn import tree #need to plot the tree#
# from sklearn.metrics import accuracy_score, recall_score, precision_score, confusion_matrix, ConfusionMatrixDisplay, f1_score
# from sklearn.neighbors import KNeighborsClassifier
# sklearn. neighbors provides functionality for unsupervised and supervised neighbors-based learning methods#
from sklearn.model_selection import train_test_split
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV, RandomizedSearchCV

In [65]:
iris = datasets.load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names) #importing dataset and making dataframe - add column names
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [66]:
df['class'] = iris.target
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     class  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [67]:
X = df.drop('class', axis=1)
y = df['class']

In [68]:
df["class"].value_counts()

class
0    50
1    50
2    50
Name: count, dtype: int64

In [69]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25,random_state=1)


class sklearn.tree.DecisionTreeClassifier(*, criterion='gini', splitter='best', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features=None, random_state=None, max_leaf_nodes=None, min_impurity_decrease=0.0, class_weight=None, ccp_alpha=0.0, monotonic_cst=None)[source]

# Online source about Implementing a Decision Tree from Scratch:
 https://www.kaggle.com/code/fareselmenshawii/decision-tree-from-scratch

# **Cross Validation on the Decision Tree Model**
1. Hold-out cross-validation
2. K-fold cross-validation
3. Stratified k-fold cross-validation
4. Leave-p-out cross-validation

# 1. Hold-out cross-validation

<img src='https://images.prismic.io/turing/65a532e47a5e8b1120d58771_image4_11zon_349fe18723.webp?auto=format,compress.png' width=500/>

# 2. K-fold Cross Validation
NOT suitable for imbalanced datasets

<img src='https://images.prismic.io/turing/6598098d531ac2845a272519_image5_11zon_af97fe4b03.webp?auto=format,compress' width=500/>


Advantages and Drawbacks of k-fold method:

Advantages:

The best part about this method is each data point gets to be in the test set exactly once and gets to be part of the training set k-1 times. As the number of folds k increases, the variance also decreases (low variance).

Drawbacks:

The major disadvantage of this method is that the model has to be run from scratch k-times and is computationally expensive than the Hold Out method.

# 3. Stratified K-fold Cross Validation
<img src= 'https://images.prismic.io/turing/65a532e87a5e8b1120d58778_image1_11zon_10bb3bd085.webp?auto=format,compress' width = 500/>

# 4. Leave-p-out cross-validation
p samples are used as the validation set and n-p samples are used as the training set if a dataset has n samples

*** Leave one out Cross Validation (LOOCV)***

<img src = "https://images.prismic.io/turing/65a532ed7a5e8b1120d5877e_image2_11zon_cac3fb4270.webp?auto=format,compress" width=500/>

Advantages and Drawbacks of Leave one Out method:

Advantages:

This method helps to reduce Bias and Randomness.

Drawbacks:

LOOCV has an extremely high variance because we are averaging the output of n-models which are fitted on an almost identical set of observations, and their outputs are highly positively correlated with each other.Also this is computationally expensive as the model is run ‘n’ times to test every observation in the data.

# **Hyperparameter Tuning**

**Using Grid Search**

See the parameters of Decision Tree: https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html

# **Random Forest Classifier**

In [70]:
from sklearn.ensemble import RandomForestClassifier

In [71]:
rfc = RandomForestClassifier(n_estimators=100)

In [72]:
rfc.fit(X_train,y_train)

RandomForestClassifier()

In [73]:
pred2 = rfc.predict(X_test)

In [74]:
print(confusion_matrix(y_test,pred2))
print('\n')
print(classification_report(y_test,pred2))

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.94      0.97        16
           2       0.90      1.00      0.95         9

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38



# **Perform Different types of Hyperparameter Tuning and Cross Validation on the Random Forest Classfied Model**
See below 5 exercises for 2 bonus point each. Total 5*2 = 10.
---



***Apply K-Fold CV ***

In [75]:
k = 5
kf_scores = cross_val_score(rfc, X_train, y_train, cv=k)

print(f"K-Fold Cross-Validation Scores (k={k}): {kf_scores}")
print(f"Mean Score: {kf_scores.mean()}")


K-Fold Cross-Validation Scores (k=5): [0.95652174 0.95652174 0.90909091 1.         0.81818182]
Mean Score: 0.9280632411067193


**Apply Stratified K-fold CV**

In [76]:
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
stratified_scores = []

for train_index, test_index in skf.split(X_train, y_train):
    X_train_fold, X_test_fold = X_train.iloc[train_index], X_train.iloc[test_index]
    y_train_fold, y_test_fold = y_train.iloc[train_index], y_train.iloc[test_index]

    rfc.fit(X_train_fold, y_train_fold)
    y_pred_fold = rfc.predict(X_test_fold)
    stratified_scores.append(accuracy_score(y_test_fold, y_pred_fold))

print(f"Stratified K-Fold Cross-Validation Scores: {stratified_scores}")
print(f"Mean Score: {np.mean(stratified_scores)}")

Stratified K-Fold Cross-Validation Scores: [0.9130434782608695, 0.9130434782608695, 1.0, 0.9545454545454546, 0.9545454545454546]
Mean Score: 0.9470355731225297


**Apply LOOCV**

In [77]:
from sklearn.model_selection import LeaveOneOut

loo = LeaveOneOut()
loo_scores = cross_val_score(rfc, X_train, y_train, cv=loo)

print(f"Mean Score: {loo_scores.mean()}")


Mean Score: 0.9375


**Apply Grid Search Hyper Parameter Tuning**

In [78]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [50, 100, 200],
    'max_features': ['sqrt', 'log2', None],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5, 10]
}

grid_search = GridSearchCV(estimator=rfc, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2)
grid_search.fit(X_train, y_train)

print(f"Best Parameters: {grid_search.best_params_}")
print(f"Best Score: {grid_search.best_score_}")


Fitting 5 folds for each of 81 candidates, totalling 405 fits
Best Parameters: {'max_depth': 10, 'max_features': 'sqrt', 'min_samples_split': 10, 'n_estimators': 50}
Best Score: 0.9553359683794467


**Apply Randomized Hyperparameter Tuning**

In [80]:
from sklearn.model_selection import RandomizedSearchCV

param_dist = {
    'n_estimators': [50, 100, 200, 300],
    'max_features': [None, 'sqrt', 'log2'],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

random_search = RandomizedSearchCV(estimator=rfc, param_distributions=param_dist, n_iter=100, cv=5, random_state=42, n_jobs=-1, verbose=2)
random_search.fit(X_train, y_train)

print(f"Best Parameters: {random_search.best_params_}")
print(f"Best Score: {random_search.best_score_}")


Fitting 5 folds for each of 100 candidates, totalling 500 fits
Best Parameters: {'n_estimators': 50, 'min_samples_split': 5, 'min_samples_leaf': 2, 'max_features': 'log2', 'max_depth': 20}
Best Score: 0.9644268774703558
